BDEPEND=test? ( dev-python/zope-interface[python_targets_pypy3(-)?,python_targets_python3_10(-)?,python_targets_python3_11(-)?,python_targets_python3_12(-)?] !dev-python/namespace-zope python_targets_pypy3? ( dev-python/unittest-or-fail[python_targets_pypy3(-)?,python_targets_python3_10(-)?,python_targets_python3_11(-)?] ) python_targets_python3_10? ( dev-python/unittest-or-fail[python_targets_pypy3(-)?,python_targets_python3_10(-)?,python_targets_python3_11(-)?] ) python_targets_python3_11? ( dev-python/unittest-or-fail[python_targets_pypy3(-)?,python_targets_python3_10(-)?,python_targets_python3_11(-)?] ) ) python_targets_pypy3? ( dev-python/pypy3:= ) python_targets_python3_10? ( dev-lang/python:3.10 ) python_targets_python3_11? ( dev-lang/python:3.11 ) python_targets_python3_12? ( dev-lang/python:3.12 ) >=dev-python/gpep517-13[python_targets_pypy3(-)?,python_targets_python3_10(-)?,python_targets_python3_11(-)?,python_targets_python3_12(-)?] >=dev-python/setuptools-67.8.0-r1[python_targets_pypy3(-)?,python_targets_python3_10(-)?,python_targets_python3_11(-)?,python_targets_python3_12(-)?]
DEFINED_PHASES=compile configure install prepare test
DESCRIPTION=General purpose exceptions for Zope packages
EAPI=8
HOMEPAGE=https://pypi.org/project/zope.exceptions/ https://github.com/zopefoundation/zope.exceptions/
INHERIT=distutils-r1 pypi
IUSE=test python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12
KEYWORDS=~amd64 ~arm ~arm64 ~ppc64 ~x86
LICENSE=ZPL
RDEPEND=dev-python/zope-interface[python_targets_pypy3(-)?,python_targets_python3_10(-)?,python_targets_python3_11(-)?,python_targets_python3_12(-)?] !dev-python/namespace-zope python_targets_pypy3? ( dev-python/pypy3:= ) python_targets_python3_10? ( dev-lang/python:3.10 ) python_targets_python3_11? ( dev-lang/python:3.11 ) python_targets_python3_12? ( dev-lang/python:3.12 )
REQUIRED_USE=|| ( python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12 )
RESTRICT=!test? ( test )
SLOT=0
SRC_URI=https://files.pythonhosted.org/packages/source/z/zope.exceptions/zope.exceptions-5.0.1.tar.gz
_eclasses_=distutils-r1	b7cd5736a595ec0df9b164d5aec6f228	flag-o-matic	ad475baa777c9978fa035216c8264a10	multibuild	30dbf3c5a31db09a19f31ad0a68f2405	multilib	c19072c3cd7ac5cb21de013f7e9832e0	multiprocessing	b4e253ab22cef7b1085e9b67c7a3b730	ninja-utils	f3010c780f65d1bb5aea15a9af1adc9c	out-of-source-utils	1a9007554652a6e627edbccb3c25a439	pypi	2eecb475512bc76e5ea9192a681b9e6b	python-r1	b3f874304c1bda6ffc3450ebb4ae5169	python-utils-r1	7661dc585f75dd1f81eccefe37bef093	toolchain-funcs	8e3fb781f3258ae2757d1dfc2c7c170e
_md5_=543be8d4e48371ab768582ccba61e52a
